title: Desk & Studio
email: www@deskandstudio.com
description: > 
  Get out of the home office and unlock your creative potential. Co-working 
  space from $75 per day plus studio/conference facilities. Phone (0438) 698 924.
baseurl: 
url: http://beta.deskandstudio.com
twitter:
  username: deskandstudio

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - bower_components
  - bower.json
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - node_modules
  - package.json
  - README.md
  - yarn.lock