---
title: Desk & Studio
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: www@deskandstudio.com
description: 'Get out of the home office and unlock your creative potential. Co-working  space
  from $50 per day plus studio/conference facilities. Phone (0438) 698 924.

'
baseurl: 
url: http://www.deskandstudio.com
twitter:
  username: deskandstudio
markdown: kramdown
plugins:
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-redirect-from
exclude:
- bower_components
- bower.json
- Gemfile
- Gemfile.lock
- gulpfile.js
- node_modules
- package.json
- README.md
- yarn.lock
