---
title: Desk & Studio
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: www@deskandstudio.com
description: Boutique photo studio with options of natural or studio lighting. Studio
  hire starting from $215 plus co-working/meeting/event facilities. Phone (0438) 698
  924.
repository: nbpayne/deskandstudio
baseurl: 
url: https://www.deskandstudio.com
twitter:
  username: deskandstudio
markdown: kramdown
plugins:
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-redirect-from
exclude:
- bower_components
- bower.json
- Gemfile
- Gemfile.lock
- gulpfile.js
- node_modules
- package.json
- README.md
- yarn.lock
formid:
  development: mQvmFOOt
  production: Xb0RIOlD
defaults:
- scope:
    path: "01-index.md"
  values:
    layout: "home"
- scope:
    path: ""
  values:
    layout: "default"