---
title: Desk & Studio
timezone: UTC
email: www@deskandstudio.com
description: Boutique photo studio with options of natural or studio lighting. Studio
  hire starting from $215 plus co-working/meeting/event facilities. Phone (0438) 698
  924.
repository: nbpayne/deskandstudio
baseurl: ""
url: https://www.deskandstudio.com
twitter:
  username: deskandstudio
markdown: kramdown
plugins:
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-sitemap
exclude:
- bower_components
- bower.json
- Gemfile
- Gemfile.lock
- gulpfile.js
- node_modules
- package.json
- README.md
- yarn.lock
formid:
  development: mQvmFOOt
  production: Xb0RIOlD
permalink: /blog/:categories/:title/
defaults:
  -
    scope:
      path: "docs/*.pdf"
    values:
      sitemap: false
    scope:
      path: "googlebb10ab82a527f8f4.html"
    values:
      sitemap: false
