---
title: Desk & Studio
timezone: UTC
email: www@deskandstudio.com
description: Boutique photo studio with options of natural or studio lighting. Studio
  hire starting from $215 plus co-working/meeting/event facilities. Phone (0438) 698
  924.
repository: nbpayne/deskandstudio
baseurl: 
url: https://www.deskandstudio.com
twitter:
  username: deskandstudio
markdown: kramdown


collections:
  staff_members:
    _hide_content: true

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      _options:
        content:
          width: 1500
          height: 2500
  -
    scope:
      path: ""
      type: "staff_members"
    values:
      _options:
        image_path:
          width: 600
          height: 600
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: "index.html"
    values:
      layout: "default"
  -
    scope:
      path: "contact.html"
    values:
      full_width: true


plugins:
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-redirect-from
exclude:
- bower_components
- bower.json
- Gemfile
- Gemfile.lock
- gulpfile.js
- node_modules
- package.json
- README.md
- yarn.lock
formid:
  development: mQvmFOOt
  production: Xb0RIOlD
